name: Vehicle Predictive Maintenance Pipeline

on:
  push:
    branches:
      - main

jobs:

  register-dataset:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Dependencies
        run: pip install -r workspace/requirements.txt

      - name: Upload Dataset to Hugging Face Hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
          PYTHONPATH: ${{ github.workspace }}
        run: python workspace/model_building/data_register.py


  data-prep:
    needs: register-dataset
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Dependencies
        run: pip install -r workspace/requirements.txt

      - name: Run Data Preparation
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
          PYTHONPATH: ${{ github.workspace }}
        run: python workspace/model_building/prep.py


  model-training:
    needs: data-prep
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Dependencies
        run: pip install -r workspace/requirements.txt

      - name: Model Building
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
          MLFLOW_TRACKING_URI: "sqlite:///mlflow.db"
          PYTHONPATH: ${{ github.workspace }}
        run: python workspace/model_building/train.py


  deploy-hosting:
    needs: [register-dataset, data-prep, model-training]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Dependencies
        run: pip install -r workspace/requirements.txt

      - name: Push files to Frontend Hugging Face Space
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
          PYTHONPATH: ${{ github.workspace }}
        run: python workspace/hosting/hosting.py
